name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Build API and Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          path: ./api/
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/api-${{ steps.extract_branch.outputs.branch }}
          tag_with_ref: true
          tag_with_sha: true

      - name: Build Front and Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/web-${{ steps.extract_branch.outputs.branch }}
          tag_with_ref: true
          tag_with_sha: true          
